export {
  UNIFIED_OUTCOME_GROUPS,
  ALL_UNIFIED_OUTCOMES,
  type UnifiedOutcomeGroup,
  SYSTEM_CALL_OUTCOMES,
  SYSTEM_CALL_STATUSES,
  SYSTEM_CALL_PURPOSES,
  SYSTEM_CALL_STATUS_DESCRIPTIONS,
  SYSTEM_CALL_OUTCOME_DESCRIPTIONS,
  type DropdownOption
} from '../utils/defaults';
